const navRoutes = {
    'leeds-property-maintenance': 'leeds-property-maintenance',
    'headingley-property-maintenance': 'headingley-property-maintenance',
    'chapeltown-property-maintenance': 'chapeltown-property-maintenance',
    'horsforth-property-maintenance': 'horsforth-property-maintenance',
    'pudsey-property-maintenance': 'pudsey-property-maintenance',
    'morley-property-maintenance': 'morley-property-maintenance',
    'halton-property-maintenance': 'halton-property-maintenance',
    'gipton-property-maintenance': 'gipton-property-maintenance',
    'kirkstall-property-maintenance': 'kirkstall-property-maintenance',
    'armley-property-maintenance': 'armley-property-maintenance',
    'burley-property-maintenance': 'burley-property-maintenance',
    'beeston-property-maintenance': 'beeston-property-maintenance',
    'hyde-park-property-maintenance': 'hyde-park-property-maintenance',
    'bramley-property-maintenance': 'bramley-property-maintenance',
    'meanwood-property-maintenance': 'meanwood-property-maintenance',
    'moortown-property-maintenance': 'moortown-property-maintenance',
    'roundhay-property-maintenance': 'roundhay-property-maintenance',
    'seacroft-property-maintenance': 'seacroft-property-maintenance',
    'harehills-property-maintenance': 'harehills-property-maintenance',
    'garforth-property-maintenance': 'garforth-property-maintenance',
    'wetherby-property-maintenance': 'wetherby-property-maintenance',
    'otley-property-maintenance': 'otley-property-maintenance',
    'yeadon-property-maintenance': 'yeadon-property-maintenance',
    'rawdon-property-maintenance': 'rawdon-property-maintenance',
    'guiseley-property-maintenance': 'guiseley-property-maintenance',
    'cross-gates-property-maintenance': 'cross-gates-property-maintenance',
    'colton-property-maintenance': 'colton-property-maintenance',
    'whinmoor-property-maintenance': 'whinmoor-property-maintenance',
    'temple-newsam-property-maintenance': 'temple-newsam-property-maintenance',
    'adel-property-maintenance': 'adel-property-maintenance',
    'alwoodley-property-maintenance': 'alwoodley-property-maintenance',
    'leckworth-property-maintenance': 'leckworth-property-maintenance',
    'leeds-city-centre-handyman': 'leeds-city-centre-handyman',
    'morley-handyman': 'morley-handyman',
    'pudsey-handyman': 'pudsey-handyman',
    'otley-handyman': 'otley-handyman'
};

module.exports = navRoutes;
